// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using StudyFlow.Api.Data;

#nullable disable

namespace StudyFlow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901175758_AddResumoNota")]
    partial class AddResumoNota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.AnatomiaChunkVector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assunto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("extensions.vector(1536)");

                    b.Property<Guid>("FonteAnatomiaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pagina")
                        .HasColumnType("integer");

                    b.Property<string>("Secao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Subassunto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "extensions.vector_cosine_ops" });

                    b.HasIndex("FonteAnatomiaId", "Pagina");

                    b.ToTable("anatomia_chunks", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.ConexaoNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NotaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("NotaOrigemId")
                        .HasColumnType("integer");

                    b.Property<string>("Rotulo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NotaDestinoId");

                    b.HasIndex("NotaOrigemId", "NotaDestinoId")
                        .IsUnique()
                        .HasDatabaseName("uq_conexao_origem_destino");

                    b.ToTable("nota_conexoes", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.FonteAnatomia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoChave")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Autor")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Publicada")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HashConteudo")
                        .IsUnique();

                    b.ToTable("fontes_anatomia", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResumoIA")
                        .HasColumnType("text");

                    b.Property<int?>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("notas", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.ResumoNota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultadoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("NotaId", "DataCriacao");

                    b.ToTable("resumos_nota", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.RevisaoNota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultadoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("NotaId", "DataCriacao");

                    b.ToTable("revisoes_nota", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("temas", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_usuarios_Email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.AnatomiaChunkVector", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.FonteAnatomia", "FonteAnatomia")
                        .WithMany("Chunks")
                        .HasForeignKey("FonteAnatomiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteAnatomia");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.ConexaoNota", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.Nota", "NotaDestino")
                        .WithMany("ConexoesDestino")
                        .HasForeignKey("NotaDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyFlow.Api.Domain.Entities.Nota", "NotaOrigem")
                        .WithMany("ConexoesOrigem")
                        .HasForeignKey("NotaOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaDestino");

                    b.Navigation("NotaOrigem");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Nota", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.Tema", "Tema")
                        .WithMany("Notas")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudyFlow.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.ResumoNota", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.Nota", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyFlow.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nota");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.RevisaoNota", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.Nota", "Nota")
                        .WithMany()
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyFlow.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nota");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Tema", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Temas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.FonteAnatomia", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Nota", b =>
                {
                    b.Navigation("ConexoesDestino");

                    b.Navigation("ConexoesOrigem");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Tema", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Temas");
                });
#pragma warning restore 612, 618
        }
    }
}
