// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyFlow.Api.Data;

#nullable disable

namespace StudyFlow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.ConexaoNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NotaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("NotaOrigemId")
                        .HasColumnType("integer");

                    b.Property<string>("Rotulo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NotaDestinoId");

                    b.HasIndex("NotaOrigemId", "NotaDestinoId")
                        .IsUnique()
                        .HasDatabaseName("uq_conexao_origem_destino");

                    b.ToTable("nota_conexoes", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResumoIA")
                        .HasColumnType("text");

                    b.Property<int>("TemaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("notas", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("temas", (string)null);
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.ConexaoNota", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.Nota", "NotaDestino")
                        .WithMany("ConexoesDestino")
                        .HasForeignKey("NotaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyFlow.Api.Domain.Entities.Nota", "NotaOrigem")
                        .WithMany("ConexoesOrigem")
                        .HasForeignKey("NotaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotaDestino");

                    b.Navigation("NotaOrigem");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Nota", b =>
                {
                    b.HasOne("StudyFlow.Api.Domain.Entities.Tema", "Tema")
                        .WithMany("Notas")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Nota", b =>
                {
                    b.Navigation("ConexoesDestino");

                    b.Navigation("ConexoesOrigem");
                });

            modelBuilder.Entity("StudyFlow.Api.Domain.Entities.Tema", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
